---
# Config File for JoinUIWorking
# Thanks for using my Plugin

# Use \n to go in a new line
# Use {player} to get player name
# Use § as a color symbole

joinui-title: "§7» §dJoinUI" # UI Title
joinui-message: "§eWelcome to this nice Server, {player}!\n§bHave fun!\n\nDo you want to edit texts and buttons?\n§fOpen the config.yml file in plugin_data folder!" # UI Text
joinui-button: "§cClose" # UI Button

enabled-joinui: "true" # If you set enabled to false, you will no longer see a UI when joining. Default is on true
no-joinui-message: "§l§eServer §r§7» §cJoinUI is disabled!" # The Message if you set "enabled-joinui" to false

# My Discord: discord.gg/bXqtHCV
...
